settings:
  server_name: Ikari
  map: Beta
  # Server Types are custom made types defined by you, make your own server type in the "Server Types" section below.
  # You can also live-set ServerTypes by doing /servertype <type>
  servertype: kitmap
  serverCurrency: £

factions:
  name:
    min: 3
    max: 16
    blocked:
      # Blcok if Contain means if a faction name contains a word in the block list, it will stop the creation of the faction.
      blockifcontain: true
      list:
        - "nigger"
        - "nigga"
        - "killyourself"
        - "kys"
        - "faggot"
        - "fag"
        - "n1gga"
        - "n1gg3r"
        - "n1gger"
  size: 16
  maxdtr: 6.5

servertypes:
  #
  # Deathban means if a player will be banned from joining after death.
  # Natural Regen means if a player can naturally regenerate health.
  # Lose DTR means if a faction can lose dtr on death.
  #
  hcf:
    deathban: true
    naturalRegen: true
    loseDTR: false
    instantRespawn: false
    startingBalance: 250
    playerDataOnSB: false

  kitmap:
    deathban: false
    naturalRegen: true
    loseDTR: false
    instantRespawn: true
    startingBalance: 500
    playerDataOnSB: true

  uhcf:
    deathban: true
    naturalRegen: false
    loseDTR: true
    instantRespawn: false
    startingBalance: 250
    playerDataOnSB: false

  uhcfkitmap:
    deathban: false
    naturalRegen: false
    loseDTR: false
    instantRespawn: true
    startingBalance: 500
    playerDataOnSB: true